### ISSUE TITLE
Vulnerable package sql used

### ISSUE THREAD

**Issue by prabhu** [covidgreen/covid-green-lambdas#1]
I scanned this repo with shiftleft scan - https://github.com/prabhu/covid-green-lambdas/runs/907302507?check_suite_focus=true#step:4:23

The repo is using @neaform/sql package which is vulnerable to SQLi attacks. Consider replacing this package with a suitable alternative. Also upgrade lodash.

Happy to send a PR if you would like to use scan permanently across your repos.

**Comment by jasnell** [comment]
The [`@nearform/sql`](https://www.npmjs.com/package/@nearform/sql) package is not the same as the [`sql`](https://www.npmjs.com/package/sql) package referenced in the shiftleft scan (which references npm [audit advisory 662](https://www.npmjs.com/advisories/662).

The lodash vulnerabilities are low severity and pose no risk in this case. Those will be updated but there's no rush to do so.

**Comment by prabhu** [comment]
Thank you. It was a false positive indeed. Please close this issue.
